const Product = require('../models/Product');

// @desc    Create a new product
// @route   POST /api/products
// @access  Protected (Admin, Manager)
exports.createProduct = async (req, res) => {
    try {
        // The Product Code is automatically generated by our Mongoose hook!
        const product = await Product.create(req.body);
        res.status(201).json({ success: true, data: product });
    } catch (error) {
        res.status(400).json({ success: false, message: error.message });
    }
};

// @desc    Get all products
// @route   GET /api/products
// @access  Protected (All Roles)
exports.getProducts = async (req, res) => {
    try {
        // Populate pulls in the actual Supplier name instead of just the ID
        const products = await Product.find().populate('supplier', 'name email');
        res.status(200).json({ success: true, count: products.length, data: products });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};